
class UpdateError(Exception):
    pass

class CustomError(Exception):
    pass